### PR TITLE
Support `foregroundColor` for `TextField`

### PR DESCRIPTION
**Pull request by carson-katri**

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@carson-katri I'm thinking of tagging a new version in the next few days with support for `async`/`await`. Would you like this PR to be included? Would you have time to address PR feedback then?

**Comment by carson-katri** [comment]
I should be able to get this finished up either tonight or tomorrow.

**Comment by MaxDesiatov** [comment]
No rush, many thanks for your contributions! 🙂

**Comment by MaxDesiatov** [comment]
Releasing 0.9.0 today, but I'm happy to tag 0.9.1 or whatever patch release it will be, later with this fix when it's ready.

**Review by MaxDesiatov — APPROVED** [review]
Nice!

**Pull request merged**
