### PR TITLE
Build the GTK renderer on Ubuntu on CI

### PR DESCRIPTION
**Pull request by MaxDesiatov**
We should make sure that our reconciler and renderer code also builds on Ubuntu.

This PR also contains some formatting changes, which were done by the latest version of SwiftFormat.

### CODE REVIEW

**Comment by mortenbekditlevsen** [comment]
Hi @MaxDesiatov ,
I recently tried building on Ubuntu 20.04 and get the same 'CRuntime' import errors.
Do you know what they are?

**Comment by MaxDesiatov** [comment]
I didn't do a very thorough investigation, seems that the Runtime dependency in OpenCombine is causing issues. I'm going to replace it with a plain `Mirror` implementation as an attempt to fix it. Just need to cherry-pick https://github.com/OpenCombine/OpenCombine/pull/201 into our fork of OpenCombine, which I'm going to do later today.

**Comment by mortenbekditlevsen** [comment]
I can now build and run TokamakGTKDemo - and it's great to see it running on Ubuntu!

Currently nothing re-renders when state changes, but I don't know if that has anything to do with the changes to OpenCombine with regards to Runtime.

**Review by mortenbekditlevsen — APPROVED** [review]
All workflow and Makefile changes looks good to me.
As I mentioned the TokamakGTKDemo does not re-render at state changes, but I don't know if that has anything to do with the 0.12.0-alpha3 version of OpenCombine or not (since I haven't been able to build on Ubuntu before).

**Comment by MaxDesiatov** [comment]
Makes sense. I think lack of updates needs to be investigated separately.

**Pull request merged**
