### PR TITLE
Fix `rootEnvironment` not merged with `.defaultEnvironment`

### PR DESCRIPTION
**Pull request by regexident**
While spelunking through the implementation of `EnvironmentValues` and its uses in Tokamak I noticed that a couple of functions were accepting a `rootEnvironment: EnvironmentValues? = nil` argument but then discarding whatever value you pass to it in favor of `.defaultEnvironment`.

This seems wrong to me? 🤔

### CODE REVIEW

**Comment by carson-katri** [comment]
Good catch. I think you may still need to add in the values `.defaultEnvironment` sets up if they are not already setup by the `rootEnvironment` though, specifically `_ToggleStyleKey`, `.colorScheme`, `._defaultAppStorage`, and `_DefaultSceneStorageProvider`.

**Comment by regexident** [comment]
Let me know if you'd rather have the merging logic as a private implementation detail. I figured since effectively every backend/renderer implementation would need it it might be worth providing a canonical method for it. Providing both `.merge(_:)` and `.merging(_:)` might a bit overkill though.

**Comment by carson-katri** [comment]
Since this isn't part of SwiftUI, may be best to make it internal with `@_spi` so the renderers can access it but users don't.

**Comment by regexident** [comment]
Absolutely! Fixed.

**Review by carson-katri — CHANGES_REQUESTED** [review]
I think you still need to add `@_spi(TokamakCore)` to some imports to fix the builds. Once that's fixed this LGTM!

**Comment by regexident** [comment]
Fixed!

**Review by MaxDesiatov — APPROVED** [review]
LGTM, thanks!

**Review by carson-katri — APPROVED** [review]

**Pull request merged**
