### PR TITLE
Simple Code Coverage analysis

### PR DESCRIPTION
**Pull request by mattpolzin**
Closes https://github.com/TokamakUI/Tokamak/issues/350.

Adds simple code coverage analysis. Until the GitHub token is set up in this repo, you can see the results including a comment on the PR here: https://github.com/mattpolzin/Tokamak/pull/2

I only commented out the tests to make the coverage diff with `main` interesting. Obviously not expecting that change to get merged :)

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
This is awesome, thanks! I wonder if coverage diffs could be posted as a GitHub Action logging command? Then it would require any tokens for comments. It would look similar to this, visible only in diffs of PRs:

screenshot

[According to the GitHub Actions docs](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message) it's enough to output a line in this form to stdout on a build agent for it to be displayed this way: `::warning file=Package.swift,line=1,col=1::Code coverage summary goes here...`. [The SwiftLint action](https://github.com/norio-nomura/action-swiftlint/blob/9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684/entrypoint.sh#L14) formats its output in a similar way.

What do you think about this approach?

**Comment by mattpolzin** [comment]
@MaxDesiatov That's an interesting idea. Makes me think it would be _really_ cool to tag the appropriate Swift file's line 1 when that file has low test coverage (or has decreased test coverage when compared to main) but that's just an idea, not something easy to support without a bit more work on the underlying coverage analysis tool.

RE your idea to log the results against the Package file, that's worth a try.  I wonder if it will syntax highlight the diff or if we want to just print the table in there without coloring (or ditch the diff idea and just print the current coverage table?). 

I'd rather have a nicer diff table, anyway, with a single `Color.swift     -19.34%` line instead of the two lines indicating `19.34%` was removed and `0%` was added -- the current diffing is just a limitation of doing this with what I've got now rather than implementing a new feature on the underlying tool.

To wrap up this message which is more about things I wish for the future than it is about the present, I can play with this more (try out the logging approach) in a few days (or possibly next weekend if I get busy). At the moment I've reached my limit for dealing with how frustrating it can be to troubleshoot random GitHub Action issues :)

**Comment by MaxDesiatov** [comment]
No problem at all, I think just logging as is against `Package.swift` (even the first line) is a good enough approach. Thanks for your hard work!

**Comment by mattpolzin** [comment]
@MaxDesiatov that seems to work; I see the annotation in the Files Changed tab at the bottom.

Would you want to always print the codecov as a warning this way or only log the warning if the coverage was too low. I suppose it could also be a warning normally and an error if the coverage was too low (which is going to fail that CI step anyway)

**Comment by MaxDesiatov** [comment]
> I suppose it could also be a warning normally and an error if the coverage was too low (which is going to fail that CI step anyway)

Yes, this makes perfect sense. Even if the coverage is improved it's convenient to observe how exactly it changed 👍

**Comment by mattpolzin** [comment]
Well, that seems to be working. On my draft PR linked in this PRs description you can see a failing result whereas this PR passes.

Final question: What do you want the minimum coverage to be initially?

If you like this where it's at, I'll uncomment those tests to get it ready for merging.

**Comment by MaxDesiatov** [comment]
As far as I understand, 20% is the current setting, LGTM. Thanks!

**Review by MaxDesiatov — APPROVED** [review]
Amazing work! 👏

**Comment by j-f1** [comment]
This is a OK start, but would it be possible to [integrate codecov](https://github.com/codecov/example-swift) so people can get a direct link to view more detailed coverage info?

**Comment by MaxDesiatov** [comment]
We've used codecov.io in the past, before SwiftUI was announced and Tokamak had a React-like API, but I found it to be not very stable overall and hard (if possible at all) to debug if coverage reports somehow don't appear in their UI. As it is a paid and apparently a VC-funded service, I'm also afraid it will eventually stop serving open-source projects like Travis did.

Maybe we could upload coverage reports to S3 or GitHub Pages instead? (In some next iteration of this)

**Comment by mattpolzin** [comment]
There might be a way to use GitHub Action artifacts to expose a public URL for the full test coverage table (percent per file).

The action already produces `./codecov.txt`. It's easy to upload that file as an artifact, but there won't be a direct link to it by name -- instead, we would need to query the GitHub rest API for artifacts related to the current workflow run and then take the right artifact's ID and plug it into `/repos/{owner}/{repo}/actions/artifacts/{artifact_id}` ourselves to produce a direct link.

**Comment by MaxDesiatov** [comment]
Thanks for taking care of this! I think it's reasonable for more advanced features to be added in separate PRs.

**Pull request merged**
