### PR TITLE
Bump requirements to Swift 5.4, migrate to `@resultBuilder`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This updates the project to use Swift 5.4 across all platforms. Swift 5.4 is now also the required version, which allows us to use `@resultBuilder` instead of the deprecated version of this attribute from Swift 5.3.

Use `carton` 0.11.0 or later from now on to build with SwiftWasm 5.4.0.

### CODE REVIEW

**Comment by ezraberch** [comment]
We can switch back to the Swift 5.4 version of SwiftLint now. You can use `mayk-it/action-swiftlint@3.2.2` for this.

**Comment by ezraberch** [comment]
Getting some new warnings:

1. `warning: in tools version 5.4.0 and later, use 'executableTarget()' to declare executable targets`

Can be fixed by switching to `executableTarget` in Package.swift for the 5 executable targets.

2. `warning: assuming you mean 'Color.red'; did you mean 'Optional<Color>.red' instead?`

I'm not exactly sure what's going on here. Seems to no longer be an issue with Xcode 13, so could just ignore for now.

3. `'CGTK' gtk+-3.0.pc: warning: prohibited flag(s): -Wl,-framework,Cocoa, -Wl,-framework,Carbon, -Wl,-framework,CoreGraphics`
`'CGDK' gdk-3.0.pc: warning: prohibited flag(s): -Wl,-framework,Cocoa, -Wl,-framework,Carbon, -Wl,-framework,CoreGraphics`

Know which flags are the problem here?

4. `warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms`

Looks like a carton issue.

**Comment by MaxDesiatov** [comment]
> Getting some new warnings:
> 
> 1. `warning: in tools version 5.4.0 and later, use 'executableTarget()' to declare executable targets`
> 
> Can be fixed by switching to `executableTarget` in Package.swift for the 5 executable targets.

Done

> 2. `warning: assuming you mean 'Color.red'; did you mean 'Optional<Color>.red' instead?`
> 
> I'm not exactly sure what's going on here. Seems to no longer be an issue with Xcode 13, so could just ignore for now.

Yup, I have no idea either, doesn't look critical at the moment

> 3. `'CGTK' gtk+-3.0.pc: warning: prohibited flag(s): -Wl,-framework,Cocoa, -Wl,-framework,Carbon, -Wl,-framework,CoreGraphics`
>    `'CGDK' gdk-3.0.pc: warning: prohibited flag(s): -Wl,-framework,Cocoa, -Wl,-framework,Carbon, -Wl,-framework,CoreGraphics`
> 
> Know which flags are the problem here?
Not sure, nothing's changed on that front in Tokamak codebase, I suspect some updates to SwiftPM in Swift 5.4 could be the culprit.


> 4. `warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms`
> 
> Looks like a carton issue.

Fixed in https://github.com/swiftwasm/carton/pull/257

**Review by ezraberch — APPROVED** [review]
Yup, looks good.

**Pull request merged**
